### ISSUE TITLE
st7789

### ISSUE THREAD

**Issue by etkanburoglu** [crystalfontz/CFAF240240A1-013T_Video#2]
Hello,
I have an st7789 and I would like to use your code to drive my screen do you think that it will be compatible since there is a version diffency and also how about the compiling error that the other users complain?
Best regards

**Comment by trevinjorg** [comment]
Hello,
It will be able to drive the screen but I would recommend changing the initialization sequence to match the display you're using. The seller should have the initialization posted somewhere for you to grab. The initialization sequence can be located in the tft.h file in an array called st_init_cmds[]. 

I was able to resolve the compiling error by changing the CMakeLists.txt file in the main folder. It's updated now, let me know if it doesn't work for you still.
