### ISSUE TITLE
raw file

### ISSUE THREAD

**Issue by rafael-meneses** [crystalfontz/CFAF240240A1-013T_Video#3]
Hi! i am trying to implement the project and i would like to know how i can generate a raw file from a video i have. Is it from some specific tool or codec?

**Comment by baxsie** [comment]
Rafael:
Thank you for your message.
That has been a while . . . we probably wrote a little utility to do some conversion from some standard format (BMP, maybe) to the raw file. The idea is that the raw file is an exact 1:1 map of the memory in the display.
Let me dig around and see if I can find that tool chain.
-Brent

**Comment by rafael-meneses** [comment]
Thank you for your help.

If possible, could you also help me understand what I might be doing wrong? I'm getting this error on sd card startup and I'm not finding help on the internet. I've already checked all connections and I'm using all files provided in the project.

And (508) vfs_fat_sdmmc: slot init failed (0x103).
E (508) main: Failed to initialize the card (259). Make sure SD card lines have pull-up resistors in place.
I (518) main: Reading file
E (518) main: Failed to open file for reading
E (528) FreeRTOS: FreeRTOS Task "SD" should not return, Aborting now!

Added the full console log below. I appreciate any support.

[outputMonitor.txt](https://github.com/crystalfontz/CFAF240240A1-013T_Video/files/7479347/outputMonitor.txt)

**Comment by baxsie** [comment]
Rafael:

Thank you for your patience.

Here is the workflow:
1) We used a video player (VLC, IIRC) to extract all the frames (14314 of them) from the 1920x1080 version of the Big Buck Bunny movie as individual bitmaps ("BMP").
2) We used a batch automated action in photoshop to crop the video to square and resample the cropped image to 240x240, then re-save that as a 240x240 24-bit bitmap. We had to break up the incoming files into folders so the photoshop action would work - there is a batch file for that. We wanted to use photoshop so the image size reduction looked good.
3) We wrote BMP_to_565_Concat to open each 240x240 bitmap, convert it to 16 bit packed (R=5,G=6,B=5) format and write those to the "BBB_565.raw" file.

Here is a link to a 7-zip (3.2GB) of that entire project folder:

https://baxsie.com/images/CFA/Github/BigBuckBunny.7z

Hopefully, that will get you going.

Peace.

-Brent

**Comment by trevinjorg** [comment]
Rafael,

That error means that the ESP32 cannot communicate with the micro SD card. Which adapter board are you using? It may be a hardware issue.

**Comment by rafael-meneses** [comment]
> Rafael:
> 
> Thank you for your patience.
> 
> Here is the workflow:
> 
> 1. We used a video player (VLC, IIRC) to extract all the frames (14314 of them) from the 1920x1080 version of the Big Buck Bunny movie as individual bitmaps ("BMP").
> 2. We used a batch automated action in photoshop to crop the video to square and resample the cropped image to 240x240, then re-save that as a 240x240 24-bit bitmap. We had to break up the incoming files into folders so the photoshop action would work - there is a batch file for that. We wanted to use photoshop so the image size reduction looked good.
> 3. We wrote BMP_to_565_Concat to open each 240x240 bitmap, convert it to 16 bit packed (R=5,G=6,B=5) format and write those to the "BBB_565.raw" file.
> 
> Here is a link to a 7-zip (3.2GB) of that entire project folder:
> 
> https://baxsie.com/images/CFA/Github/BigBuckBunny.7z
> 
> Hopefully, that will get you going.
> 
> Peace.
> 
> -Brent

Understand. Very grateful for your help.

👏👏👏

**Comment by rafael-meneses** [comment]
> Rafael,
> 
> That error means that the ESP32 cannot communicate with the micro SD card. Which adapter board are you using? It may be a hardware issue.

the components are these:

[TFT](https://www.crystalfontz.com/product/cfaf240240a1013t-240x240-color-tft-lcd-display) 
[Card Reader](https://www.crystalfontz.com/product/cfa10112-sd-card-reader) 
and a ESP32

**Comment by trevinjorg** [comment]
Rafael,

I think the micro SD card must be faulty. Would you open a ticket with technical support at Crystalfontz and mention this issue? https://www.crystalfontz.com/contact.php

I'll make sure we send you a tested replacement part.

**Comment by rafael-meneses** [comment]
Hi! I did the test with two boards of the same model and unfortunately I had the same problem.

thanks for your help.
